sudo: false
language: c

matrix:
  include:
    - env: NGXVER=head CABALVER=head GHCVER=head
      compiler: gcc
      addons:
        apt:
          packages: [cabal-install-head, ghc-head]
          sources: [hvr-ghc]
    - env: NGXVER=1.14.0 CABALVER=head GHCVER=8.4.3
      compiler: gcc
      addons:
        apt:
          packages: [cabal-install-head, ghc-8.4.3]
          sources: [hvr-ghc]
    - env: NGXVER=1.12.2 CABALVER=head GHCVER=8.4.3
      compiler: gcc
      addons:
        apt:
          packages: [cabal-install-head, ghc-8.4.3]
          sources: [hvr-ghc]
    - env: CABALVER=head GHCVER=head
      addons:
        apt:
          packages: [cabal-install-head, ghc-head]
          sources: [hvr-ghc]
    - env: CABALVER=head GHCVER=8.6.1
      addons:
        apt:
          packages: [cabal-install-head, ghc-8.6.1]
          sources: [hvr-ghc]
    - env: CABALVER=head GHCVER=8.4.3
      addons:
        apt:
          packages: [cabal-install-head, ghc-8.4.3]
          sources: [hvr-ghc]
    - env: CABALVER=head GHCVER=8.2.2
      addons:
        apt:
          packages: [cabal-install-head, ghc-8.2.2]
          sources: [hvr-ghc]
    - env: CABALVER=head GHCVER=8.0.2
      addons:
        apt:
          packages: [cabal-install-head, ghc-8.0.2]
          sources: [hvr-ghc]
    - env: CABALVER=head GHCVER=7.10.3
      addons:
        apt:
          packages: [cabal-install-head, ghc-7.10.3]
          sources: [hvr-ghc]
  allow_failures:
    - env: NGXVER=head CABALVER=head GHCVER=head
    - env: CABALVER=head GHCVER=head

before_install:
  - |
    set -e
    export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
    if [ -n "$NGXVER" ]
    then
        cpanm -v --notest --local-lib=~/perl5 local::lib Test::Nginx &&
            eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
        export PATH=~/.cabal/bin:$PATH
    fi
    set +e

install:
  - |
    set -e
    cabal --version
    echo "$(ghc --version) "`
        `"[$(ghc --print-project-git-commit-id 2>/dev/null || echo '?')]"
    travis_retry cabal v1-update
    cd haskell/ngx-export
    cabal v1-install --only-dependencies
    if [ -n "$NGXVER" ]
    then
        cd -
        if [ "$NGXVER" == head ]
        then
            git clone https://github.com/nginx/nginx.git nginx-head
        else
            wget http://nginx.org/download/nginx-${NGXVER}.tar.gz &&
                tar xzvf nginx-${NGXVER}.tar.gz
        fi
        git clone https://github.com/openresty/echo-nginx-module.git
        cabal v1-install cpphs regex-pcre-builtin aeson bytestring safe
        cd -
    elif [ "$GHCVER" != "7.10.3" ]
    then
        cd -
        cd haskell/ngx-export-tools
        cabal v1-install --only-dependencies
        cd -
        cd haskell/ngx-export
    fi
    set +e

script:
  - |
    set -e
    cabal v1-configure
    cabal v1-build
    cabal v1-sdist
    SRC_TGZ=$(cabal info . | awk '{print $2; exit}').tar.gz &&
        (cd dist && cabal v1-install --force-reinstalls "$SRC_TGZ")
    if [ -n "$NGXVER" ]
    then
        cd -
        cd nginx-${NGXVER}/
        if [ "$NGXVER" == head ]
        then
            NGX_CONFIGURE=./auto/configure
        else
            NGX_CONFIGURE=./configure
        fi
        $NGX_CONFIGURE --add-module=.. --add-module=../echo-nginx-module
        make -j2
        export PATH=$(pwd)/objs:$PATH
        cd -
        cd test
        set +e
        prove -r t-travis
    elif [ "$GHCVER" != "7.10.3" ]
    then
        cd -
        cd haskell/ngx-export-tools
        cabal v1-configure
        cabal v1-build
        cabal v1-sdist
        SRC_TGZ=$(cabal info . | awk '{print $2; exit}').tar.gz &&
            (cd dist && cabal v1-install --force-reinstalls "$SRC_TGZ")
    fi
    set +e

